config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/logowanie' => 'panel/sessions#new'
  get '/wyloguj' => 'panel/sessions#destroy'

  get '/panel' => 'panel/dashboard#cockpit'
  get 'panel/ogloszenia' => 'panel/dashboard#advertisments'
  get 'panel/oferty' => 'panel/dashboard#offers'
  get 'panel/profil' => 'panel/dashboard#profil'
  get 'panel/ustawienia' => 'panel/dashboard#settings'
  get 'panel/weryfikacja' => 'panel/dashboard#verify'
  get 'panel/dodaj-ogloszenie' => 'panel/advertisments#new'


  namespace :panel do
    resources :dashboard, only: [:cockpit, :advertisments, :offers, :profile, :settings, :verify]
    resources :sessions, only: [:new, :create, :destroy]
    resources :advertisments, only: [:new, :create, :edit, :update]
  end

end

app/models/advertisment.rb
class Advertisment < ActiveRecord::Base
  belongs_to :user

  has_many :offers
  has_many :advertisment_categories
  has_many :categories, through: :advertisment_categories
  has_many :advertisment_geolocations
  has_many :geolocations, through: :advertisment_geolocations

  before_create :set_ended_date

  def set_ended_date
  	self.ended = Time.now + 30.days
  end

end

app/models/advertisment_category.rb
class AdvertismentCategory < ActiveRecord::Base
  belongs_to :advertisment
  belongs_to :category
end

app/models/advertisment_geolocation.rb
class AdvertismentGeolocation < ActiveRecord::Base
  belongs_to :advertisment
  belongs_to :geolocation
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :advertisment_categories
	has_many :advertisments, through: :advertisment_categories
end

app/models/geolocation.rb
class Geolocation < ActiveRecord::Base
	has_many :advertisment_geolocations
	has_many :advertisments, through: :advertisment_geolocations
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :advertisment
end

app/models/panel.rb
module Panel
  def self.table_name_prefix
    'panel_'
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :advertisments
	has_many :offers

	extend FriendlyId
	friendly_id :login, use: :slugged

	validates :email, presence: true, uniqueness: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/panel/advertisments_controller.rb
class Panel::AdvertismentsController < Panel::ApplicationController
  def new
  	@advertisment = Advertisment.new
  	@categories = Category.all
  	@geolocations = Geolocation.all
  end

  def create
  	advertisment = Advertisment.new(strong_params)
  	advertisment.user_id = session[:user_id]
  	if advertisment.save
  		redirect_to panel_ogloszenia_path(status: 'waiting_mod'), notice: 'Dodano nowe ogłoszenie, któro oczekuję na moderację'
		else
			flash[:alert] = 'Wystąpił problem z dodaniem nowego ogłoszenia'
			render :new
  	end
  end

  def edit
  end

  def update
  end

  private

  def strong_params
  	params.require(:advertisment)
  		.permit(:title, :content, :category_ids, :geolocation_ids, :price, :realization)
  end
end

app/controllers/panel/application_controller.rb
class Panel::ApplicationController < ApplicationController
	layout 'panel'

	before_action :authorize

	helper_method :current_user, :logged_in?

	def current_user
		@user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authorize
		unless current_user
			redirect_to new_panel_session_path, alert: "Prosimy o zalgowanie się"
		end
	end

	def logged_in?
		current_user != nil
	end

end

app/controllers/panel/dashboard_controller.rb
class Panel::DashboardController < Panel::ApplicationController
  def cockpit
  	@active_advertisments_count = active_advertisments.count
  	@wating_advertisments_count = waiting_winner_advertisments.count
  	@ended_advertisments_count = ended_advertisments.count
  end

  def advertisments
  	if params[:status].present?
  		case params[:status]
  		when 'waiting_winner'
	  		@title = 'Oczekujące na zwycięzce'
        @layout = 'winner'
        @advertisments = waiting_winner_advertisments.page(params[:page]).per(5)
      when 'waiting_mod'
        @layout = 'mod'
        @title = 'Oczekujące na moderacje'
        @advertisments = waiting_moderation_advertisments.page(params[:page]).per(5)
      when 'ended'
        @layout = 'ended'
        @title = 'Zakończone ogłoszenia'
        @advertisments = ended_advertisments.page(params[:page]).per(5)
      end
    else
  		@title = 'Aktywne ogłoszenia'
	  	@advertisments = active_advertisments.page(params[:page]).per(5)
	  end
  end

  def offers
  	if params[:status].present?
  		case params[:status]
  		when 'waiting_winner'
		  	@advertisments = Advertisment.joins(:offers)
					.where(closed: true).where(winner: nil)
					.where(offers: {user_id: session[:user_id]}).page(params[:page]).per(5)		
  		when 'won'
  			@advertisments = Advertisment.joins(:offers)
					.where(closed: true).where(winner: session[:user_id])
					.where(offers: {user_id: session[:user_id]}).page(params[:page]).per(5)	
			end
		else
			@advertisments = Advertisment.joins(:offers)
				.where(status: true).where(closed: false)
				.where(offers: {user_id: session[:user_id]}).page(params[:page]).per(5)
  	end
  end

  def profile
  	
  end

  protected

  def waiting_moderation_advertisments
  	Advertisment.where(status: false)
	  		.where(user_id: session[:user_id]).order(ended: :asc)
  end

  def active_advertisments
  	Advertisment.where(status: true).where(closed: false)
	  		.where(user_id: session[:user_id]).order(ended: :asc)
  end

  def waiting_winner_advertisments
  	Advertisment.where(closed: true).where(winner: nil)
		  		.where(user_id: session[:user_id]).order(ended: :asc)
  end

  def ended_advertisments
  	Advertisment.where(closed: true).where.not(winner: nil)
		  		.where(user_id: session[:user_id]).order(ended: :asc)
  end
end

app/controllers/panel/sessions_controller.rb
class Panel::SessionsController < Panel::ApplicationController

	layout 'login'

	before_action :authorize, except: [:new, :create]

  def new
  end

  def create
  	user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to panel_path, notice: 'Poprawnie zalogowanio do panelu'
  	else
  		flash[:alert] = 'Prosimy o podanie prawidłowego e-mail i hasła'
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to new_panel_session_path, notice: 'Poprawnie wylogowano'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def date_issue date
		date.strftime('%d-%m-%Y')
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/panel/advertisments_helper.rb
module Panel::AdvertismentsHelper
	def days_to_left advertisment
		days = ((advertisment.ended - advertisment.created_at)/1.day).to_i
		case days
		when 1
			"1 dzień"
		else
			"#{days} dni"
		end
	end
end

app/helpers/panel/dashboard_helper.rb
module Panel::DashboardHelper
end

app/helpers/panel/sessions_helper.rb
module Panel::SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zlecenie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- favicon -->
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- TOP WRAPPER -->
		
	<%= render 'shared/top' %>
	
	<!-- /TOP WRAPPER -->

	<div class="clearfix"></div>

	<!-- MAIN CONTENT -->

	<section class="main-content">
		<div class="center">
		
			<%= render 'shared/notice_alert' %>
		
			<!-- Sidebar -->
		
			<%= render 'shared/sidebar' %>
			
			<!-- /Sidebar -->

			<!-- Content -->
			
			<%= yield %>
			
			<!-- /Content -->
			
		</div>
	</section>

	<!-- /MAIN CONTENT -->

	<div class="clearfix"></div>

	<!-- BOTTOM -->

	<%= render 'shared/bottom' %>

	<!-- /BOTTOM -->

	<div class="clearfix"></div>

	<!-- FOOTER -->
	
	<%= render 'shared/footer' %>

	<!-- /FOOTER -->

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zlecenie</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- favicon -->
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- TOP WRAPPER -->
		
	<%= render 'shared/top' %>
	
	<!-- /TOP WRAPPER -->

	<div class="clearfix"></div>

	<!-- MAIN CONTENT -->

	<section class="main-content login-page">
		<div class="center">
		
		<%= render 'shared/notice_alert' %>

			<%= yield %>

		</div>
	</section>

	<!-- /MAIN CONTENT -->

	<div class="clearfix"></div>

	<!-- BOTTOM -->

	<%= render 'shared/bottom' %>

	<!-- /BOTTOM -->

	<div class="clearfix"></div>

	<!-- FOOTER -->
	
	<%= render 'shared/footer' %>

	<!-- /FOOTER -->

</body>
</html>

app/views/layouts/panel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zlecenie</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- favicon -->
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- TOP WRAPPER -->
		
	<%= render 'shared/top' %>
	
	<!-- /TOP WRAPPER -->

	<div class="clearfix"></div>

	<!-- MAIN CONTENT -->

	<section class="main-content">
		<div class="center">
		
		<%= render 'shared/notice_alert' %>
		
			<!-- Sidebar -->
		
			<%= render 'shared/panel/sidebar' %>
			
			<!-- /Sidebar -->

			<!-- Content -->
			
			<%= yield %>
			
			<!-- /Content -->
			
		</div>
	</section>

	<!-- /MAIN CONTENT -->

	<div class="clearfix"></div>

	<!-- BOTTOM -->

	<%= render 'shared/bottom' %>

	<!-- /BOTTOM -->

	<div class="clearfix"></div>

	<!-- FOOTER -->
	
	<%= render 'shared/footer' %>

	<!-- /FOOTER -->

</body>
</html>

app/views/panel/advertisments/edit.html.erb
<h1>Panel::Advertisments#edit</h1>
<p>Find me in app/views/panel/advertisments/edit.html.erb</p>

app/views/panel/advertisments/new.html.erb
<div class="three-fourth main-text panel-content last">
	<span class="font-18px skin-font-color1 bold">Dodaj ogłoszenie</span>
		
	<%= form_for [:panel, @advertisment], class: 'add-new-commission' do |f| %>
		<span class="skin-font-color15 font-14px semibold">ZLECENIE:</span><span class="font-14px semibold main-subtitle">Tytuł ogłoszenia</span>
		<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-1">Podaj tytuł</span>
		<%= f.text_field :title, class: 'skin-background-color1 skin-font-color3', placeholder: 'Tytuł ogłoszenia' %>
		<span class="font-14px semibold main-subtitle">Treść ogłoszenia</span>
		<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-2">Podaj treść ogłoszenia</span>
		<%= f.text_area :content, class: 'skin-background-color1 skin-font-color3', placeholder: 'Treść ogłoszenia' %>		
		<div class="skin-background-color5 line-break"></div>
		<div class="one-third">
			<span class="font-14px semibold main-subtitle">Kategoria</span>
			<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-3">Wybierz pole</span>
			<%= f.collection_select(:category_ids, @categories, :id, :name, {prompt: 'Wybierz z listy'}, {class: 'skin-background-color1 skin-font-color3'}) %>
		</div>
		<div class="one-third">
			<span class="font-14px semibold main-subtitle">Lokalizacja</span>
			<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-4">Wybierz pole</span>
			<%= f.collection_select(:geolocation_ids, @geolocations, :id, :name, {:prompt => 'Wybierz z listy'}, {class: 'skin-background-color1 skin-font-color3'}) %>
		</div>
		<div class="one-third last">
			<span class="font-14px semibold main-subtitle">Budżet</span>
			<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-5">Wybierz pole</span>
			<%= f.select :price, options_for_select([['50zł - 300zł', '50-300'], ['301zł - 1000zł', '301-1000'], ['1001zł - 3000zł', '1001-3000'], ['3001zł - 10000zł', '3001-10000'], ['powyżej 10000zł', '10000+']]), {include_blank: "Select something", prompt: 'Wybierz z listy'}, {class: 'skin-background-color1 skin-font-color3' }%>
		</div>
		
		<div class="clearfix"></div>
		
		<div class="one-third">
			<span class="font-14px semibold main-subtitle">Czas trwania</span>
			<span class="panel-content-error skin-background-color12 skin-font-color2 bold error-7">Wybierz pole</span>
			<%= f.select :realization, options_for_select([['7 dni', 7], ['14 dni', 14], ['21 dni', 21], ['30 dni', 30], ['60 dni', 60]]), {prompt: 'Wybierz z listy'}, {class: 'skin-background-color1 skin-font-color3' }%>
		</div>
		
		<div class="skin-background-color5 line-break"></div>
		
		<div class="submit">
			<%= f.submit "Dodaj ogłoszenie", class: 'skin-background-color12 skin-font-color2 skin-background-hover6 font-11px bold' %>
			<div class="submit-text">
				<span class="bold">Dodając akceptujesz </span><a href="#" class="bold skin-font-color14 skin-color-hover1">regulamin</a><span class="bold">.</span>
			</div>
		</div>
		
	<% end %>
	
</div>

app/views/panel/dashboard/_advertisments_active.html.erb
<% if @advertisments.any? %>
	<ul class="ad-list">
		<% @advertisments.each do |advertisment| %>
			<li class="ad-prev">
				<span class="skin-font-color9 semibold font-12px">Zlecenie: </span><span class="semibold font-12px"><%= advertisment.title %></span>
				<div class="meta-info">
					<span class="bold">Kategorie: </span><span class="second-span">
					<% advertisment.categories.each do |category| %>
						<%= category.name %>
					<% end %>
					</span>
					<span class="bold">Lokalizacja: </span><span class="second-span">
						<% advertisment.geolocations.each do |geolocation| %>
							<%= geolocation.name %>
						<% end %>
					</span>
					<span class="bold">Budżet: </span><span class="second-span"><%= advertisment.price %>zł</span> 	
					<span class="bold">Wystawione: </span><span class="second-span"><%= date_issue advertisment.created_at %></span> 
					<span class="bold">Do końca: </span><span class="second-span"><%= days_to_left advertisment %></span>
					<span class="bold">Ilość ofert: </span><span class="second-span"><%= advertisment.offers.count %></span> 
				</div>
				<a href="#" class="button skin-font-color2 skin-background-color9 skin-background-hover1 bold">Zobacz ogłoszenie</a>
				<a href="#" class="button skin-font-color2 skin-background-color3 skin-background-hover1 bold">Edytuj</a>
				<a href="#" class="button skin-font-color2 skin-background-color3 skin-background-hover1 bold">Zakończ</a>
			</li>
		<% end %>
	</ul>
<% else %>
<%= render 'empty' %>
<% end %>

app/views/panel/dashboard/_advertisments_ended.html.erb
<% if @advertisments.any? %>
	<ul class="ad-list">
		<% @advertisments.each do |advertisment| %>
			<li class="ad-prev">
				<span class="skin-font-color9 semibold font-12px">Zlecenie: </span><span class="semibold font-12px"><%= advertisment.title %></span>
				<div class="meta-info">
					<span class="bold">Kategorie: </span><span class="second-span">
					<% advertisment.categories.each do |category| %>
						<%= category.name %>
					<% end %>
					</span>
					<span class="bold">Lokalizacja: </span><span class="second-span">
						<% advertisment.geolocations.each do |geolocation| %>
							<%= geolocation.name %>
						<% end %>
					</span>
					<span class="bold">Budżet: </span><span class="second-span"><%= advertisment.price %>zł</span> 
					<span class="bold">Zakończone: </span><span class="second-span"><%= advertisment.ended.strftime('%Y-%m-%d') %></span> 
				</div>
				<a href="#" class="button skin-font-color2 skin-background-color9 skin-background-hover1 bold">Zobacz ogłoszenie</a>
			</li>
		<% end %>
	</ul>
<% else %>
	<%= render 'empty' %>
<% end %>

app/views/panel/dashboard/_advertisments_mod.html.erb
<% if @advertisments.any? %>
	<ul class="ad-list">
		<% @advertisments.each do |advertisment| %>
			<li class="ad-prev">
				<span class="skin-font-color9 semibold font-12px">Zlecenie: </span><span class="semibold font-12px"><%= advertisment.title %></span>
				<div class="meta-info">
					<span class="bold">Kategorie: </span><span class="second-span">
					<% advertisment.categories.each do |category| %>
						<%= category.name %>
					<% end %>
					</span>
					<span class="bold">Lokalizacja: </span><span class="second-span">
						<% advertisment.geolocations.each do |geolocation| %>
							<%= geolocation.name %>
						<% end %>
					</span>
					<span class="bold">Budżet: </span><span class="second-span"><%= advertisment.price %>zł</span> 	
					<span class="bold">Wystawione: </span><span class="second-span"><%= date_issue advertisment.created_at %></span>
				</div>
			</li>
		<% end %>
	</ul>
<% else %>
	<%= render 'empty' %>
<% end %>

app/views/panel/dashboard/_advertisments_winner.html.erb
<% if @advertisments.any? %>
<ul class="ad-list">
	<% @advertisments.each do |advertisment| %>
	<li class="ad-prev">
		<span class="skin-font-color15 semibold font-12px">Zlecenie: </span><span class="semibold font-12px"><%= advertisment.title %></span>
		<div class="meta-info">
			<span class="bold">Kategorie: </span><span class="second-span">
			<% advertisment.categories.each do |category| %>
				<%= category.name %>
			<% end %>
			</span>
			<span class="bold">Lokalizacja: </span><span class="second-span">
				<% advertisment.geolocations.each do |geolocation| %>
					<%= geolocation.name %>
				<% end %>
			</span>
			<span class="bold">Budżet: </span><span class="second-span"><%= advertisment.price %>zł</span>
			<span class="bold">Wystawione: </span><span class="second-span"><%= date_issue advertisment.created_at %></span>  
			<span class="bold">Do końca: </span><span class="second-span"><%= days_to_left advertisment %></span>
			<span class="bold">Ilość ofert: </span><span class="second-span"><%= advertisment.offers.count %></span>
		</div>
		<a href="#" class="button skin-font-color2 skin-background-color14 skin-background-hover1 bold">Zobacz ogłoszenie</a>
		<a href="#" class="button skin-font-color2 skin-background-color3 skin-background-hover1 bold">Wybierz zwycięzcę</a>
	</li>
	<% end %>
</ul>
<% else %>
	<%= render 'empty' %>
<% end %>

app/views/panel/dashboard/_empty.html.erb
<p>
	Brak Ogłoszeń
</p>

app/views/shared/_top.html.erb
<section class="top-wrapper skin-background-color1 skin-font-color2">
	<div class="top">
		<div class="center">
			<%= image_tag('logo.png', alt: 'logo', class: 'logo') %>
			<ul class="logo-menu">
				<li><a href="#" class="skin-font-color4 skin-color-hover2 bold">Zlecenia</a></li>
				<li><a href="#" class="skin-font-color3 skin-color-hover2">Usługi</a></li>
				<li><a href="#" class="skin-font-color3 skin-color-hover2">Praca</a></li>
				<li><a href="#" class="skin-font-color3 skin-color-hover2">Współpraca</a></li>
			</ul>

			<%= render 'shared/user_logged' %>
			
		</div>
	</div>
	<div class="top-menu skin-background-color3">
		<div class="center">
			<ul class="choose skin-border-color2">
				<li><a href="#" class="skin-font-color1 skin-background-hover2 menu-current">Strona Główna</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Strony internetowe</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Grafika</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Aplikacje</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Administracja, wdrożenia</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Prace edytorskie</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Marketing, reklama</a></li>
				<li><a href="#" class="skin-font-color1 skin-background-hover2">Pozostałe</a></li>
			</ul>
			<ul class="buttons">
				<li><a href="#" class="skin-font-color2 skin-background-color9 skin-background-hover2 skin-color-hover1 bold choose-mobile-button">Główne menu</a></li>
				<li>
					<%= link_to "Dodaj ogłoszenie", panel_dodaj_ogloszenie_path, class: 'skin-font-color1 skin-background-color4 skin-background-hover2 bold' %>
					</li>
			</ul>
		</div>
	</div>
	
	<ul class="mobile-menu">
		<li><a href="#" class="skin-font-color2 skin-color-hover2 menu-current bold">Strona Główna</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Strony internetowe</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Grafika</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Aplikacje</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Administracja, wdrożenia</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Prace edytorskie</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Marketing, reklama</a></li>
		<li><a href="#" class="skin-font-color2 skin-color-hover2">Pozostałe</a></li>
		<li><a href="#" class="skin-font-color9 skin-color-hover2 bold mobile-user">Zarejestruj sie</a></li>
		<li><a href="#" class="skin-font-color9 skin-color-hover2 bold mobile-user">Zaloguj sie</a></li>
	</ul>
	
</section>

app/views/shared/_user_logged.html.erb
<% if logged_in? %>
	<div class="user-logged">
		<div class="user-logged-options">
			<span class="bold skin-font-color2">Zalogowany jako: </span><span class="bold skin-font-color12"><%= current_user.login %></span>
			<ul>
				<li><%= link_to "~Kokpit", panel_path, class: 'skin-font-color3 skin-color-hover2' %></li>
				<li><%= link_to "~Wyloguj", wyloguj_path, class: 'skin-font-color3 skin-color-hover2' %></li>
			</ul>
		</div>
		<div class="logo-wrapp">
			<img src="images/avatar/1.jpg" alt="profile">
		</div>
	</div>
<% else %>
	<ul class="user-menu bold">
		<li><%= link_to "Zarejestruj się", logowanie_path, class: 'skin-font-color2 skin-color-hover2' %></li>
		<li><%= link_to "Zaloguj się", logowanie_path, class: 'skin-font-color2 skin-color-hover2' %></li>
	</ul>
<% end %>

app/views/shared/panel/_sidebar.html.erb
<div class="one-fourth main-sidebar">
	<div class="sidebar">
		<span class="font-18px skin-font-color1 bold">Panel użytkownika</span>
		<ul class="panel-menu">
			<li class="skin-border-color5">
				<%= link_to "Kokpit", panel_path, class: 'skin-font-color1 skin-background-hover8' %>
			</li>
			<!-- <li class="skin-border-color5"><a href="#" class="skin-font-color1 skin-background-hover8 panel-menu-current bold">Kokpit</a></li> -->
			<li class="skin-border-color5"><a class="skin-font-color1 bold">Twoje ogłoszenia</a>
				<ul>
					<!-- <li><%#= link_to "Aktywne", panel_ogloszenia_path, class: 'skin-font-color9 bold' %></li> -->
					<li>
						<%= link_to "/ Oczekujące na moderacje", panel_ogloszenia_path(status: 'waiting_mod'), class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<li>
						<%= link_to "/ Aktywne", panel_ogloszenia_path, class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<li>
						<%= link_to "/ Oczekujące na zwycięzce", panel_ogloszenia_path(status: 'waiting_winner'), class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<li>
						<%= link_to "/ Zakończone", panel_ogloszenia_path(status: 'ended'), class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<!-- <li><a href="#" class="skin-font-color1 skin-color-hover4">/ Archiwum</a></li> -->
				</ul>
			</li>
			<li class="skin-border-color5"><a class="skin-font-color1 bold">Twoje oferty</a>
				<ul>
					<li>
						<%= link_to "/ Aktywne", panel_oferty_path, class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<li>
						<%= link_to "/ Oczekujące na zwycięzce", panel_oferty_path(status: 'waiting_winner'), class: 'skin-font-color1 skin-background-hover8' %>
					</li>
					<li>
						<%= link_to "/ Wygrane", panel_oferty_path(status: 'won'), class: 'skin-font-color1 skin-background-hover8' %>
					</li>
				</ul>
			</li>
			<li class="skin-border-color5">
				<%= link_to "Profil wykonawcy", panel_profil_path, class: 'skin-font-color1 skin-background-hover8' %>
			</li>
			<li class="skin-border-color5">
				<%= link_to "Ustawienia konta", panel_ustawienia_path, class: 'skin-font-color1 skin-background-hover8' %>
			</li>
			<li class="skin-border-color5">
				<%= link_to "Weryfikacja", panel_weryfikacja_path, class: 'skin-font-color1 skin-background-hover8' %>
			</li>
		</ul>
	</div>
	<div class="sidebar">
		<span class="font-18px skin-font-color1 bold">Pomoc</span>
		<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vitae urna augue. Fusce eget ligula ligula. Nulla auctor mauris non quam congue iaculis. Nulla imperdiet sit amet ipsum et euismod. Mauris dapibus lacus in urna tempus, et vestibulum urna varius.</p>
	</div>
</div>